---
# defaults file for cockroach

binary_url: https://binaries.cockroachdb.com
binary_version: "{{ install_version }}.tgz"
install_location: /var/lib/cockroach
cockroach_port: 26257
http_port: 8080
reinstall_cluster: False
