---
# tasks file for cockroach-db

- name: Create databases
  cockroach_db: name={{ database }} path={{ install_location }}/{{ install_version }} host={{ private_ip }} state=present
  when: private_ip == cluster_master and database is defined
  tags: create_db



