---
# Set postgresql state when configuration changes are made. Recommended values:
# `restarted` or `reloaded`
postgresql_restarted_state: "restarted"

postgresql_python_library: python-psycopg2

postgresql_hba_entries:
  - {type: local, database: all, user: postgres, auth_method: peer}
  - {type: local, database: all, user: all, auth_method: peer}
  - {type: host, database: all, user: all, address: '127.0.0.1/32', auth_method: md5}
  - {type: host, database: all, user: all, address: '::1/128', auth_method: md5}
  - {type: host, database: all, user: all, address: '0.0.0.0/0', auth_method: md5}
  - {type: host, database: all, user: all, address: '::0/0', auth_method: trust}

postgresql_user: postgres
postgresql_group: postgres

# Global configuration options that will be set in postgresql.conf.
postgresql_global_config_options:
  - option: unix_socket_directories
    value: '{{ postgresql_unix_socket_directories | join(",") }}'

postgresql_unix_socket_directories:
  - /var/run/postgresql

# Debian only. Locale support refers to an application respecting cultural preferences regarding alphabets,
# sorting, number formatting, etc...
postgresql_locales:
  - 'en_US.UTF-8'

backup_path: "/Users/camelot/workspace/deployment-databases/ansible/backup.sql"

postgresql_service_state: started
postgresql_service_enabled: true

# Databases to ensure exist.
postgresql_databases:
  - name: octo # required; the rest are optional
    extension_gen_uuid: pgcrypto
#   lc_collate: # defaults to 'en_US.UTF-8'
#   lc_ctype: # defaults to 'en_US.UTF-8'
#   encoding: # defaults to 'UTF-8'
#   template: # defaults to 'template0'
#   login_host: # defaults to 'localhost'
#   login_password: # defaults to not set
#   login_user: # defaults to '{{ postgresql_user }}'
#   login_unix_socket: # defaults to 1st of postgresql_unix_socket_directories
#   port: # defaults to not set
#   owner: # defaults to postgresql_user
#   state: # defaults to 'present'

# Users to ensure exist.
postgresql_users:
  - name: camelot #required; the rest are optional
    password: 'jw8s0F4' # defaults to not set
#   encrypted: # defaults to not set
#   priv: # defaults to not set
    role_attr_flags: SUPERUSER # defaults to not set
    db: octo # defaults to not set
#   login_host: # defaults to 'localhost'
#   login_password: # defaults to not set
#   login_user: # defaults to '{{ postgresql_user }}'
#   login_unix_socket: # defaults to 1st of postgresql_unix_socket_directories
#   port: 3306 # defaults to not set
#   state: # defaults to 'present'
