---
# tasks file for host-setup
- name: Generate /etc/hosts
  template: src=etc-hosts.j2 dest=/etc/hosts backup=false
  tags: etc_hosts

- name: Install ntp
  raw: apt -y update && apt install -y ntp
  tags: ntp

- name: Install ntpdate
  raw: apt -y update && apt install -y ntpdate
  tags: ntp

- name: Make sure ntp is running
  service: name=ntp state=running
  tags: ntp/

- name: Sync clocks
  shell: "ntpdate -u 0.rhel.pool.ntp.org"
  when: sync_clocks
  tags: ntp

- name: get file stat to be able to perform a check in the following task
  local_action: stat path="{{ ssh_local }}"
  register: file

- name: Copy ssh to acces to instances
  copy:
    src:  "{{ ssh_local }}"
    dest: "{{ ssh_remote }}"
    mode: 0777
  when: file.stat.exists